export const GETUSERS_REQUEST = 'GETUSERS_REQUEST';
export const GETUSERS_SUCCESS = 'GETUSERS_SUCCESS';
export const GETUSERS_FAIL = 'GETUSERS_FAIL';

export const GETTODO_REQUEST = 'GETTODO_REQUEST';
export const GETTODO_SUCCESS = 'GETTODO_SUCCESS';
export const GETTODO_FAIL = 'GETTODO_FAIL';

export const GIVEREMARK_REQUEST = 'GIVEREMARK_REQUEST';
export const GIVEREMARK_SUCCESS = 'GIVEREMARK_SUCCESS';
export const GIVEREMARK_FAIL = 'GIVEREMARK_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

