export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GETTASKS_REQUEST = "GETTASKS_REQUEST";
export const GETTASKS_SUCCESS = "GETTASKS_SUCCESS";
export const GETTASKS_FAIL = "GETTASKS_FAIL";

export const ADDTASK_REQUEST = "ADDTASK_REQUEST";
export const ADDTASK_SUCCESS = "ADDTASK_SUCCESS";
export const ADDTASK_FAIL = "ADDTASK_FAIL";

export const UPDATETASK_REQUEST = "UPDATETASK_REQUEST";
export const UPDATETASK_SUCCESS = "UPDATETASK_SUCCESS";
export const UPDATETASK_FAIL = "UPDATETASK_FAIL";

export const DELETETASK_REQUEST = "DELETETASK_REQUEST";
export const DELETETASK_SUCCESS = "DELETETASK_SUCCESS";
export const DELETETASK_FAIL = "DELETETASK_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

